### ISSUE TITLE
search for wrong variable 

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#162]
subset countries is mixing up the variables, when resources are contains different variables

2017-01-26 11:38:25,566 - flyingpigeon.subset - ERROR - ocgis clipping failed for PRCPTOT_EUR-44_MPI-M-MPI-ESM-LR_historical_r2i1p1_MPI-CSC-REMO2009_v1_AMJJAS_19870701-19870701 
Traceback (most recent call last):
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/subset.py", line 150, in clipping
    memory_limit=memory_limit, time_range=time_range, time_region=time_region,
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/ocgis_module.py", line 136, in call
    add_auxiliary_files=False)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pywps/Wps/Execute/../../../ocgis/api/operations.py", line 186, in __init__
    self._is_init = False
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pywps/Wps/Execute/../../../ocgis/api/operations.py", line 219, in __setattr__
    self._validate_()
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pywps/Wps/Execute/../../../ocgis/api/operations.py", line 365, in _validate_
    projections.append(rd.crs)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pywps/Wps/Execute/../../../ocgis/api/request/base.py", line 282, in crs
    ret = self.driver.get_crs()
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pywps/Wps/Execute/../../../ocgis/api/request/driver/nc.py", line 81, in get_crs
    crs = potential.load_from_metadata(get_tuple(self.rd.variable)[0], self.rd.source_metadata)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pywps/Wps/Execute/../../../ocgis/api/request/base.py", line 320, in source_metadata
    self._source_metadata = self.driver.get_source_metadata()
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pywps/Wps/Execute/../../../ocgis/api/request/driver/nc.py", line 130, in get_source_metadata
    raise VariableNotFoundError(self.rd.uri, variables[0])
VariableNotFoundError: The variable "TG" was not found in the dataset with URI: /home/nils/birdhouse/var/lib/pywps/tmp/flyingpigeon/pywps-instanceXXTnSd/./PRCPTOT_EUR-44_MPI-M-MPI-ESM-LR_historical_r2i1p1_MPI-CSC-REMO2009_v1_AMJJAS_ref-all.nc

**Comment by nilshempelmann** [comment]
Fixed. 
Disabled Variabel as literal input. 
the variable name is now always detected for each dataset
