### ISSUE TITLE
request data 'certificate verify failed'

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#183]
weatherregime_projection is fetching output data from precalculated waetherregime processes. 
Fetch failed: 
2017-07-17 19:54:07,134 - PYWPS - ERROR - failed to download data
Traceback (most recent call last):
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/utils.py", line 156, in download
    filename = download_file(url)
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/utils.py", line 126, in download_file
    r = requests.get(url, stream=True)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by nilshempelmann** [comment]
fixed with 
request.get(url, verify=False)
