### ISSUE TITLE
iris implementation failed  

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#225]
@huard: Can we get rid of iris?
 
used in unrotate_pole (related with this also in get_coordinate)
____________________________________________________________________________ test_unrotate_pole ____________________________________________________________________________
Traceback (most recent call last):
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/tests/test_utils.py", line 75, in test_unrotate_pole
    lats,  lons = utils.unrotate_pole(ncs)
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/utils.py", line 955, in unrotate_pole
    from iris.analysis import cartography as ct
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/__init__.py", line 111, in <module>
    import iris.cube
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/cube.py", line 40, in <module>
    import iris.analysis
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/analysis/__init__.py", line 61, in <module>
    from iris.analysis._area_weighted import AreaWeightedRegridder
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/analysis/_area_weighted.py", line 23, in <module>
    from iris.analysis._interpolation import get_xy_dim_coords, snapshot_grid
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/analysis/_interpolation.py", line 31, in <module>
    from iris.analysis.cartography import wrap_lons as wrap_circular_points
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/analysis/cartography.py", line 29, in <module>
    import cf_units
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/cf_units/__init__.py", line 401, in <module>
    _status_msg, _error_msg))
OSError: [UT_PARSE] Failed to open UDUNITS-2 XML unit database 
___________________________________________________________________________ test_get_coordinates ___________________________________________________________________________
Traceback (most recent call last):
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/tests/test_utils.py", line 94, in test_get_coordinates
    lats, lons = utils.get_coordinates(ncs, unrotate=True)
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/utils.py", line 521, in get_coordinates
    lats, lons = unrotate_pole(resource)
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/utils.py", line 955, in unrotate_pole
    from iris.analysis import cartography as ct
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/__init__.py", line 111, in <module>
    import iris.cube
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/cube.py", line 40, in <module>
    import iris.analysis
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/analysis/__init__.py", line 61, in <module>
    from iris.analysis._area_weighted import AreaWeightedRegridder
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/analysis/_area_weighted.py", line 23, in <module>
    from iris.analysis._interpolation import get_xy_dim_coords, snapshot_grid
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/analysis/_interpolation.py", line 31, in <module>
    from iris.analysis.cartography import wrap_lons as wrap_circular_points
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/iris/analysis/cartography.py", line 29, in <module>
    import cf_units
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/cf_units/__init__.py", line 44, in <module>
    from . import config
ImportError: cannot import name config

**Comment by huard** [comment]
I'm not using it anywhere, so no objection.

**Comment by nilshempelmann** [comment]
Yes you do :-) : used in 'eggshell' as well. netcdf_utils ocgis_utils and visualization

**Comment by huard** [comment]
Darn. But I guess you could remove it in FP and leave it in eggshell.

**Comment by nilshempelmann** [comment]
I agree with continue to develop in eggshell, adding appropriate tests there and get it ready to run. 
FP can than be streamlined and functions replaced there by eggshell.functions.

**Comment by huard** [comment]
This is fixed (at least for FP) in the eggshell_dep branch.
