### ISSUE TITLE
test fetch modis data

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#233]
http://www.pymodis.org/_images/ipython_example.png

**Comment by nilshempelmann** [comment]
Traceback (most recent call last):
  File "/home/nils/.conda/envs/flyingpigeon/bin/modis_download.py", line 153, in <module>
    main()
  File "/home/nils/.conda/envs/flyingpigeon/bin/modis_download.py", line 147, in main
    modisOgg.downloadsAllDay(clean=options.empty, allDays=options.alldays)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pymodis/downmodis.py", line 849, in downloadsAllDay
    self._downloadAllDaysHTTP(days)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pymodis/downmodis.py", line 865, in _downloadAllDaysHTTP
    self.dayDownload(day, listFilesDown)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pymodis/downmodis.py", line 827, in dayDownload
    self.downloadFile(i, file_hdf, day)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pymodis/downmodis.py", line 676, in downloadFile
    self._downloadFileHTTP(filDown, filHdf, day)
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/site-packages/pymodis/downmodis.py", line 699, in _downloadFileHTTP
    re=e.reason))
KeyError: 'ex'
