### ISSUE TITLE
Install fails due to ImportError libhdf5_cpp.so.102

### ISSUE THREAD

**Issue by nkadygrov** [bird-house/flyingpigeon#253]
## Description

Install fails due to ImportError ... see below.

## Steps to Reproduce

```
$ make clean install
Develop: '/home/sthao/birdhouse/flyingpigeon/.'
Traceback (most recent call last):
  File "/tmp/tmpx50lBz", line 14, in <module>
    exec(compile(f.read(), '/home/sthao/birdhouse/flyingpigeon/./setup.py', 'exec'))
  File "/home/sthao/birdhouse/flyingpigeon/./setup.py", line 5, in <module>
    version = __import__('flyingpigeon').__version__
  File "/home/sthao/birdhouse/flyingpigeon/./flyingpigeon/__init__.py", line 1, in <module>
    from .wsgi import application
  File "/home/sthao/birdhouse/flyingpigeon/./flyingpigeon/wsgi.py", line 4, in <module>
    from .processes import processes
  File "/home/sthao/birdhouse/flyingpigeon/./flyingpigeon/processes/__init__.py", line 1, in <module>
    from .wps_subset_countries import ClippingProcess
  File "/home/sthao/birdhouse/flyingpigeon/./flyingpigeon/processes/wps_subset_countries.py", line 1, in <module>
    from flyingpigeon.subset import clipping
  File "/home/sthao/birdhouse/flyingpigeon/./flyingpigeon/subset.py", line 5, in <module>
    from flyingpigeon.utils import drs_filename, get_variable, calc_grouping, sort_by_filename
  File "/home/sthao/birdhouse/flyingpigeon/./flyingpigeon/utils.py", line 8, in <module>
    from ocgis import RequestDataset  # does not support NETCDF4
  File "/home/sthao/.conda/envs/flyingpigeon/lib/python2.7/site-packages/ocgis/__init__.py", line 5, in <module>
    import osgeo
  File "/home/sthao/.conda/envs/flyingpigeon/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/sthao/.conda/envs/flyingpigeon/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: libhdf5_cpp.so.102: cannot open shared object file: No such file or directory
While:
  Installing.
  Processing develop directory '/home/sthao/birdhouse/flyingpigeon/.'.
```

**Comment by cehbrecht** [comment]
need to focus on the new FP, can't fix the old one.
