### ISSUE TITLE
Tests for subset countries continents (clipping function)

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#282]
Processes are running fine, but test are failing

**Comment by nilshempelmann** [comment]
error message: 
```
Traceback (most recent call last):
  File "/home/nils/anaconda3/envs/flyingpigeon/lib/python3.7/site-packages/pywps/app/Process.py", line 22
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/processes/wps_subset_continents.py", line 107, in 
    raise Exception(msg)
Exception: Clipping failed: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by nilshempelmann** [comment]
@huard Are the test really running locally on your side?

**Comment by huard** [comment]
@nilshempelmann Yes

**Comment by huard** [comment]
Weird, when I run them within the entire test suite, they fail, when I run them individually, they pass...

**Comment by huard** [comment]
The issue seems to be triggered by `test_wps_spatial_analog`. I think the `setUp` and `tearDown` methods are the culprit.

**Comment by nilshempelmann** [comment]
@huard I see. good to have the problem identified.
