### ISSUE TITLE
brocken test_wps_subset_bbox

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#322]
## Description

```
Traceback (most recent call last):
  File "/home/nils/birdhouse/flyingpigeon/tests/test_wps_subset_bbox.py", line 28, in test_wps_subset_bbox
    check_bnds(ds['lat_bnds'], 2, 4)
  File "netCDF4/_netCDF4.pyx", line 2377, in netCDF4._netCDF4.Dataset.__getitem__
IndexError: lat_bnds not found in /
```

**Comment by nilshempelmann** [comment]
reason?: 
```
exceptionCode="NoApplicableCode" locator="None">\n           nText>Process error: method=wps_subset_bbox.py._handler, line=80, UDUNITS-2 XML unit database</ows:ExceptionText>\n 
```

**Comment by tlvu** [comment]
> IndexError: lat_bnds not found in /

@nilshempelmann I don't think I can help with this error.
