### ISSUE TITLE
tar file preparation failed in simple indices

### ISSUE THREAD

**Issue by nilshempelmann** [bird-house/flyingpigeon#78]
PyWPS [2016-08-23 12:01:01,262] ERROR: Tar file preparation failed
Traceback (most recent call last):
  File "/home/nils/birdhouse/flyingpigeon/flyingpigeon/processes/wps_indices_simple.py", line 129, in execute
    tar.add( result , arcname = os.path.basename(result))
  File "/home/nils/.conda/envs/flyingpigeon/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
AttributeError: 'list' object has no attribute 'rfind'

**Comment by nilshempelmann** [comment]
Fixed.
